export interface Spot {
  id: string;
  name: string;
  category: 'restaurant' | 'activity' | 'bar' | 'cafe' | 'nightlife' | 'wellness';
  cuisine?: string;
  description: string;
  priceLevel: 1 | 2 | 3 | 4;
  rating: number;
  image: string;
  tags: string[];
  // Preference filters
  isOutdoor: boolean;
  smokingFriendly: boolean;
  vibeLevel: 'chill' | 'moderate' | 'active'; // chill = relaxed, active = moving around
}

export interface Preferences {
  location: 'indoor' | 'outdoor' | 'both';
  smoking: 'yes' | 'no' | 'doesnt-matter';
  vibe: 'chill' | 'active' | 'both';
  fancy: 'fancy' | 'divey' | 'both';
  distance: 'walking' | 'short-drive' | 'road-trip' | 'any';
}

export interface GameState {
  mode: 'landing' | 'setup' | 'preferences' | 'playing' | 'results';
  playerCount: number;
  currentPlayer: number;
  spots: Spot[];
  remainingSpots: Spot[];
  votes: Record<string, number>;
  winner: Spot | null;
  category: 'all' | 'restaurant' | 'activity' | 'bar' | 'cafe' | 'nightlife' | 'wellness';
  preferences: Preferences;
}

export const SAMPLE_SPOTS: Spot[] = [
  // RESTAURANTS
  {
    id: '1',
    name: 'Golden Dragon',
    category: 'restaurant',
    cuisine: 'Chinese',
    description: 'Authentic Szechuan cuisine with a modern twist',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=400',
    tags: ['Spicy', 'Family-friendly', 'Dine-in'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '2',
    name: 'Bella Italia',
    category: 'restaurant',
    cuisine: 'Italian',
    description: 'Handmade pasta and wood-fired pizzas',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
    tags: ['Romantic', 'Wine Bar', 'Outdoor Seating'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '3',
    name: 'Taco Fiesta',
    category: 'restaurant',
    cuisine: 'Mexican',
    description: 'Street-style tacos and fresh margaritas',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    tags: ['Casual', 'Quick Bites', 'Late Night'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '4',
    name: 'Sakura Sushi',
    category: 'restaurant',
    cuisine: 'Japanese',
    description: 'Premium sushi and omakase experience',
    priceLevel: 4,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400',
    tags: ['Fine Dining', 'Fresh Seafood', 'Sake Bar'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '5',
    name: 'The Rustic Burger',
    category: 'restaurant',
    cuisine: 'American',
    description: 'Gourmet burgers with craft beer selection',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=400',
    tags: ['Burgers', 'Craft Beer', 'Sports Bar'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: '6',
    name: 'Garden Terrace BBQ',
    category: 'restaurant',
    cuisine: 'BBQ',
    description: 'Smoky ribs and brisket in an open-air setting',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400',
    tags: ['BBQ', 'Outdoor', 'Groups'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '7',
    name: 'Seoul Kitchen',
    category: 'restaurant',
    cuisine: 'Korean',
    description: 'Interactive Korean BBQ with premium meats',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
    tags: ['Korean BBQ', 'Interactive', 'Group Dining'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '8',
    name: 'Mediterranean Breeze',
    category: 'restaurant',
    cuisine: 'Mediterranean',
    description: 'Fresh mezze and grilled seafood by the water',
    priceLevel: 3,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
    tags: ['Seafood', 'Waterfront', 'Healthy'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },

  // ACTIVITIES
  {
    id: '9',
    name: 'Strike Zone Bowling',
    category: 'activity',
    description: 'Modern bowling alley with arcade games',
    priceLevel: 2,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?w=400',
    tags: ['Group Fun', 'Arcade', 'Birthday Parties'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '10',
    name: 'Escape Room Adventures',
    category: 'activity',
    description: 'Thrilling escape rooms for all skill levels',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400',
    tags: ['Team Building', 'Mystery', 'Challenging'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '11',
    name: 'Craft & Canvas',
    category: 'activity',
    description: 'Paint and sip classes for beginners',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400',
    tags: ['Creative', 'BYOB', 'Date Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '12',
    name: 'Urban Hiking Trail',
    category: 'activity',
    description: 'Scenic city trails with stunning views',
    priceLevel: 1,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400',
    tags: ['Nature', 'Exercise', 'Free'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'active',
  },
  {
    id: '13',
    name: 'Sunset Kayaking',
    category: 'activity',
    description: 'Paddle through calm waters at golden hour',
    priceLevel: 2,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
    tags: ['Water Sports', 'Romantic', 'Adventure'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '14',
    name: 'Mini Golf Paradise',
    category: 'activity',
    description: 'Glow-in-the-dark mini golf with themes',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400',
    tags: ['Family Fun', 'Competitive', 'Casual'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: '15',
    name: 'Botanical Gardens',
    category: 'activity',
    description: 'Peaceful stroll through beautiful gardens',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400',
    tags: ['Nature', 'Photography', 'Relaxing'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '16',
    name: 'Trampoline Park',
    category: 'activity',
    description: 'Jump, flip, and bounce at this high-energy spot',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1626716493137-b67fe9501e76?w=400',
    tags: ['High Energy', 'Kids Friendly', 'Workout'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '17',
    name: 'Board Game Cafe',
    category: 'activity',
    description: 'Hundreds of games to play with snacks & drinks',
    priceLevel: 1,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1632501641765-e568d28b0015?w=400',
    tags: ['Games', 'Cozy', 'All Ages'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '18',
    name: 'Rock Climbing Gym',
    category: 'activity',
    description: 'Indoor climbing walls for all skill levels',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400',
    tags: ['Fitness', 'Challenge', 'Beginner Friendly'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '19',
    name: 'Beach Volleyball Courts',
    category: 'activity',
    description: 'Drop-in games and leagues at the beach',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400',
    tags: ['Sports', 'Social', 'Beach'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'active',
  },
  {
    id: '20',
    name: 'Pottery Workshop',
    category: 'activity',
    description: 'Learn to throw clay and create your own pieces',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
    tags: ['Creative', 'Hands-on', 'Unique'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },

  // BARS
  {
    id: '21',
    name: 'The Speakeasy',
    category: 'bar',
    description: 'Hidden cocktail bar with 1920s vibes',
    priceLevel: 3,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400',
    tags: ['Cocktails', 'Live Jazz', 'Intimate'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '22',
    name: 'Rooftop Lounge',
    category: 'bar',
    description: 'Stunning city views with craft cocktails',
    priceLevel: 3,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400',
    tags: ['Views', 'Trendy', 'Happy Hour'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '23',
    name: 'The Beer Garden',
    category: 'bar',
    description: 'Outdoor patio with 50+ craft beers on tap',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1575037614876-c38a4c44374e?w=400',
    tags: ['Craft Beer', 'Outdoor', 'Dog Friendly'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '24',
    name: 'Karaoke Box',
    category: 'bar',
    description: 'Private karaoke rooms with full bar service',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
    tags: ['Karaoke', 'Private Rooms', 'Party'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '25',
    name: 'Wine & Cheese Bar',
    category: 'bar',
    description: 'Curated wine flights with artisan cheese boards',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    tags: ['Wine', 'Sophisticated', 'Date Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '26',
    name: 'Tiki Lounge',
    category: 'bar',
    description: 'Tropical cocktails in a beach-themed paradise',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400',
    tags: ['Tiki', 'Fun Drinks', 'Themed'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },

  // CAFES
  {
    id: '27',
    name: 'The Cozy Bean',
    category: 'cafe',
    description: 'Artisan coffee and fresh pastries',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400',
    tags: ['Coffee', 'WiFi', 'Study Spot'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '28',
    name: 'Garden Cafe',
    category: 'cafe',
    description: 'Organic brunch in a botanical setting',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=400',
    tags: ['Brunch', 'Vegan Options', 'Instagram-worthy'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '29',
    name: 'Sidewalk Espresso',
    category: 'cafe',
    description: 'European-style sidewalk cafe for people watching',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
    tags: ['Espresso', 'Outdoor Seating', 'European'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '30',
    name: 'Cat Cafe Purrfection',
    category: 'cafe',
    description: 'Sip coffee while cuddling adoptable cats',
    priceLevel: 2,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    tags: ['Cats', 'Unique', 'Cozy'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },

  // NIGHTLIFE
  {
    id: '31',
    name: 'Club Neon',
    category: 'nightlife',
    description: 'High-energy dance club with top DJs',
    priceLevel: 3,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?w=400',
    tags: ['Dancing', 'DJ', 'Late Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '32',
    name: 'Live Music Venue',
    category: 'nightlife',
    description: 'Intimate concerts and emerging artists',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    tags: ['Live Music', 'Indie', 'Standing Room'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '33',
    name: 'Comedy Club',
    category: 'nightlife',
    description: 'Laugh out loud with stand-up comedy shows',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=400',
    tags: ['Comedy', 'Entertainment', '21+'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '34',
    name: 'Pool Hall & Lounge',
    category: 'nightlife',
    description: 'Upscale billiards with craft cocktails',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1604948501466-4e9c339b9c24?w=400',
    tags: ['Pool', 'Competitive', 'Chill'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: '35',
    name: 'Hookah Lounge',
    category: 'nightlife',
    description: 'Relaxed atmosphere with premium hookah & tea',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400',
    tags: ['Hookah', 'Lounge', 'Social'],
    isOutdoor: false,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '36',
    name: 'Outdoor Cinema',
    category: 'nightlife',
    description: 'Movies under the stars with blankets & snacks',
    priceLevel: 2,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    tags: ['Movies', 'Romantic', 'Seasonal'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },

  // WELLNESS
  {
    id: '37',
    name: 'Hot Springs Spa',
    category: 'wellness',
    description: 'Natural hot springs with massage services',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    tags: ['Spa', 'Relaxation', 'Healing'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '38',
    name: 'Yoga in the Park',
    category: 'wellness',
    description: 'Outdoor yoga sessions for all levels',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    tags: ['Yoga', 'Outdoor', 'Peaceful'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '39',
    name: 'Float Tank Center',
    category: 'wellness',
    description: 'Sensory deprivation tanks for deep relaxation',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    tags: ['Unique', 'Meditation', 'Wellness'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '40',
    name: 'Sound Bath Studio',
    category: 'wellness',
    description: 'Healing sound sessions with singing bowls',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    tags: ['Sound Healing', 'Meditation', 'Spiritual'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
];
