export interface Spot {
  id: string;
  name: string;
  category: 'restaurant' | 'activity' | 'bar' | 'cafe' | 'nightlife' | 'wellness' | 'brunch' | 'lunch' | 'dinner' | 'desserts' | 'shopping' | 'event';
  cuisine?: string;
  description: string;
  priceLevel: 1 | 2 | 3 | 4;
  rating: number;
  image: string;
  tags: string[];
  neighborhood?: string;
  plusOnly?: boolean;
  // Preference filters
  isOutdoor: boolean;
  smokingFriendly: boolean;
  vibeLevel: 'chill' | 'moderate' | 'active' | 'dancing' | 'lazy'; // energy level of the spot
  // Location
  latitude?: number;
  longitude?: number;
  distance?: number; // miles from user
}

// --- Quick Vibe types ---
export type VibeIntent = 'food' | 'drinks' | 'activity' | 'shopping' | 'events' | 'services' | 'surprise';
export type VibeEnergy = 'chill' | 'social' | 'romantic' | 'adventure' | 'productive' | 'self-care' | 'weird';
export type VibeFilter = 'cheap' | 'mid' | 'treat' | 'indoor' | 'outdoor' | 'near-me' | 'any-distance';

export type ShoppingSubcategory = 'random' | 'decor' | 'clothes' | 'games' | 'books' | 'gifts' | 'vintage' | 'artisan';

// 7 user-facing vibes that map internally to intent/energy
export type YouPickVibe = 'reset' | 'momentum' | 'golden-hour' | 'explore' | 'soft-social' | 'full-send' | 'free-beautiful';

export interface YouPickVibeInfo {
  id: YouPickVibe;
  label: string;
  subtitle: string;
  emoji: string;
  // Internal mapping (hidden from user)
  mappedIntent: VibeEnergy;
  mappedEnergy: 'low' | 'medium' | 'high' | 'low-medium';
}

export const YOUPICK_VIBES: YouPickVibeInfo[] = [
  { id: 'reset', label: 'Reset', subtitle: 'Ground, breathe, recalibrate.', emoji: '🧘', mappedIntent: 'chill', mappedEnergy: 'low' },
  { id: 'momentum', label: 'Momentum', subtitle: 'Get moving. Build a spark.', emoji: '⚡', mappedIntent: 'adventure', mappedEnergy: 'medium' },
  { id: 'golden-hour', label: 'Golden Hour', subtitle: 'Cinematic. Scenic. Aesthetic.', emoji: '🌅', mappedIntent: 'romantic', mappedEnergy: 'low-medium' },
  { id: 'explore', label: 'Explore', subtitle: 'Unexpected. Curious. Different.', emoji: '🧭', mappedIntent: 'adventure', mappedEnergy: 'medium' },
  { id: 'soft-social', label: 'Soft Social', subtitle: 'Connection, low pressure.', emoji: '☕', mappedIntent: 'social', mappedEnergy: 'low-medium' },
  { id: 'full-send', label: 'Full Send', subtitle: 'Bold. Loud. Out tonight.', emoji: '🔥', mappedIntent: 'adventure', mappedEnergy: 'high' },
  { id: 'free-beautiful', label: 'Free & Beautiful', subtitle: 'Low-cost outdoor magic.', emoji: '🌿', mappedIntent: 'self-care', mappedEnergy: 'low' },
];

// Map user-facing vibe to internal intent/energy for backend
export function vibeToInternalMapping(vibe: YouPickVibe | null): { intent: VibeEnergy | null; energy: string | null } {
  if (!vibe) return { intent: null, energy: null };
  const info = YOUPICK_VIBES.find(v => v.id === vibe);
  if (!info) return { intent: null, energy: null };
  return { intent: info.mappedIntent, energy: info.mappedEnergy === 'low' ? 'chill' : info.mappedEnergy === 'high' ? 'adventure' : 'social' };
}

export interface VibeInput {
  intent: VibeIntent | null;
  energy: VibeEnergy | null;
  filters: VibeFilter[];
  shoppingSubcategory?: ShoppingSubcategory | null;
  selectedVibe?: YouPickVibe | null;
}

export type RandomnessLevel = 'wild' | 'balanced' | 'specific';

export function computeRandomness(vibe: VibeInput): RandomnessLevel {
  if (vibe.intent === 'surprise' || (!vibe.intent && !vibe.energy && vibe.filters.length === 0)) {
    return 'wild';
  }
  const specificity = (vibe.intent ? 1 : 0) + (vibe.energy ? 1 : 0) + Math.min(vibe.filters.length, 3);
  if (specificity >= 3) return 'specific';
  return 'balanced';
}

// Map intent → category for filtering
export function intentToCategories(intent: VibeIntent | null): string[] {
  switch (intent) {
    case 'food': return ['restaurant', 'cafe', 'bakery', 'food-truck', 'brunch', 'lunch', 'dinner', 'desserts'];
    case 'drinks': return ['bar', 'nightlife', 'cocktail-lounge', 'wine-bar', 'dive-bar', 'rooftop-bar'];
    case 'activity': return ['activity', 'park', 'museum', 'bowling', 'arcade', 'escape-room', 'golf', 'mini-golf', 'hiking', 'workshop'];
    case 'shopping': return ['shopping', 'retail', 'boutique', 'thrift', 'market', 'vintage', 'mall'];
    case 'events': return ['event', 'concert', 'festival', 'live-music', 'art-show', 'pop-up'];
    case 'services': return ['wellness', 'spa', 'yoga', 'fitness', 'gym', 'meditation', 'massage'];
    case 'surprise': return [];
    case null: return [];
    default: return [];
  }
}

export interface Preferences {
  location: 'indoor' | 'outdoor' | 'both';
  smoking: 'yes' | 'no' | 'doesnt-matter';
  vibe: 'chill' | 'active' | 'dancing' | 'lazy' | 'both';
  fancy: 'fancy' | 'divey' | 'both';
  distance: 'walking' | 'short-drive' | 'road-trip' | 'epic-adventure' | 'any';
  mood: 'solo' | 'date' | 'squad' | 'chaotic' | 'cozy' | 'any';
  budget: 'budget' | 'mid' | 'splurge' | 'any';
  fortunePack: 'free' | 'plus' | 'love' | 'career' | 'unhinged' | 'main_character';
  freeOnly: boolean;
}

export interface GameState {
  mode: 'landing' | 'vibe' | 'setup' | 'preferences' | 'playing' | 'results';
  vibeStep: 0 | 1 | 2; // 0=intent, 1=energy, 2=filters
  vibeInput: VibeInput;
  playerCount: number;
  currentPlayer: number;
  spots: Spot[];
  remainingSpots: Spot[];
  votes: Record<string, number>;
  likedSpots: Spot[];
  winner: Spot | null;
  category: 'all' | 'restaurant' | 'activity' | 'bar' | 'cafe' | 'nightlife' | 'wellness' | 'brunch' | 'lunch' | 'dinner' | 'desserts' | 'shopping' | 'event';
  preferences: Preferences;
}

export const SAMPLE_SPOTS: Spot[] = [
  // RESTAURANTS
  {
    id: '1',
    name: 'Golden Dragon',
    category: 'restaurant',
    cuisine: 'Chinese',
    description: 'Authentic Szechuan cuisine with a modern twist',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=400',
    tags: ['Spicy', 'Family-friendly', 'Dine-in'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '2',
    name: 'Bella Italia',
    category: 'restaurant',
    cuisine: 'Italian',
    description: 'Handmade pasta and wood-fired pizzas',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
    tags: ['Romantic', 'Wine Bar', 'Outdoor Seating'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '3',
    name: 'Taco Fiesta',
    category: 'restaurant',
    cuisine: 'Mexican',
    description: 'Street-style tacos and fresh margaritas',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    tags: ['Casual', 'Quick Bites', 'Late Night'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '4',
    name: 'Sakura Sushi',
    category: 'restaurant',
    cuisine: 'Japanese',
    description: 'Premium sushi and omakase experience',
    priceLevel: 4,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400',
    tags: ['Fine Dining', 'Fresh Seafood', 'Sake Bar'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '5',
    name: 'The Rustic Burger',
    category: 'restaurant',
    cuisine: 'American',
    description: 'Gourmet burgers with craft beer selection',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=400',
    tags: ['Burgers', 'Craft Beer', 'Sports Bar'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: '6',
    name: 'Garden Terrace BBQ',
    category: 'restaurant',
    cuisine: 'BBQ',
    description: 'Smoky ribs and brisket in an open-air setting',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400',
    tags: ['BBQ', 'Outdoor', 'Groups'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '7',
    name: 'Seoul Kitchen',
    category: 'restaurant',
    cuisine: 'Korean',
    description: 'Interactive Korean BBQ with premium meats',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
    tags: ['Korean BBQ', 'Interactive', 'Group Dining'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '8',
    name: 'Mediterranean Breeze',
    category: 'restaurant',
    cuisine: 'Mediterranean',
    description: 'Fresh mezze and grilled seafood by the water',
    priceLevel: 3,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
    tags: ['Seafood', 'Waterfront', 'Healthy'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },

  // ACTIVITIES
  {
    id: '9',
    name: 'Strike Zone Bowling',
    category: 'activity',
    description: 'Modern bowling alley with arcade games',
    priceLevel: 2,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?w=400',
    tags: ['Group Fun', 'Arcade', 'Birthday Parties'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '10',
    name: 'Escape Room Adventures',
    category: 'activity',
    description: 'Thrilling escape rooms for all skill levels',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400',
    tags: ['Team Building', 'Mystery', 'Challenging'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '11',
    name: 'Craft & Canvas',
    category: 'activity',
    description: 'Paint and sip classes for beginners',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400',
    tags: ['Creative', 'BYOB', 'Date Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '12',
    name: 'Urban Hiking Trail',
    category: 'activity',
    description: 'Scenic city trails with stunning views',
    priceLevel: 1,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400',
    tags: ['Nature', 'Exercise', 'Free'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'active',
  },
  {
    id: '13',
    name: 'Sunset Kayaking',
    category: 'activity',
    description: 'Paddle through calm waters at golden hour',
    priceLevel: 2,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
    tags: ['Water Sports', 'Romantic', 'Adventure'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '14',
    name: 'Mini Golf Paradise',
    category: 'activity',
    description: 'Glow-in-the-dark mini golf with themes',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400',
    tags: ['Family Fun', 'Competitive', 'Casual'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: '15',
    name: 'Botanical Gardens',
    category: 'activity',
    description: 'Peaceful stroll through beautiful gardens',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400',
    tags: ['Nature', 'Photography', 'Relaxing'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '16',
    name: 'Trampoline Park',
    category: 'activity',
    description: 'Jump, flip, and bounce at this high-energy spot',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1626716493137-b67fe9501e76?w=400',
    tags: ['High Energy', 'Kids Friendly', 'Workout'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '17',
    name: 'Board Game Cafe',
    category: 'activity',
    description: 'Hundreds of games to play with snacks & drinks',
    priceLevel: 1,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1632501641765-e568d28b0015?w=400',
    tags: ['Games', 'Cozy', 'All Ages'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '18',
    name: 'Rock Climbing Gym',
    category: 'activity',
    description: 'Indoor climbing walls for all skill levels',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400',
    tags: ['Fitness', 'Challenge', 'Beginner Friendly'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '19',
    name: 'Beach Volleyball Courts',
    category: 'activity',
    description: 'Drop-in games and leagues at the beach',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400',
    tags: ['Sports', 'Social', 'Beach'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'active',
  },
  {
    id: '20',
    name: 'Pottery Workshop',
    category: 'activity',
    description: 'Learn to throw clay and create your own pieces',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
    tags: ['Creative', 'Hands-on', 'Unique'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },

  // BARS
  {
    id: '21',
    name: 'The Speakeasy',
    category: 'bar',
    description: 'Hidden cocktail bar with 1920s vibes',
    priceLevel: 3,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400',
    tags: ['Cocktails', 'Live Jazz', 'Intimate'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '22',
    name: 'Rooftop Lounge',
    category: 'bar',
    description: 'Stunning city views with craft cocktails',
    priceLevel: 3,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400',
    tags: ['Views', 'Trendy', 'Happy Hour'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '23',
    name: 'The Beer Garden',
    category: 'bar',
    description: 'Outdoor patio with 50+ craft beers on tap',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1575037614876-c38a4c44374e?w=400',
    tags: ['Craft Beer', 'Outdoor', 'Dog Friendly'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '24',
    name: 'Karaoke Box',
    category: 'bar',
    description: 'Private karaoke rooms with full bar service',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
    tags: ['Karaoke', 'Private Rooms', 'Party'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '25',
    name: 'Wine & Cheese Bar',
    category: 'bar',
    description: 'Curated wine flights with artisan cheese boards',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    tags: ['Wine', 'Sophisticated', 'Date Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '26',
    name: 'Tiki Lounge',
    category: 'bar',
    description: 'Tropical cocktails in a beach-themed paradise',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400',
    tags: ['Tiki', 'Fun Drinks', 'Themed'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },

  // CAFES
  {
    id: '27',
    name: 'The Cozy Bean',
    category: 'cafe',
    description: 'Artisan coffee and fresh pastries',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400',
    tags: ['Coffee', 'WiFi', 'Study Spot'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '28',
    name: 'Garden Cafe',
    category: 'cafe',
    description: 'Organic brunch in a botanical setting',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=400',
    tags: ['Brunch', 'Vegan Options', 'Instagram-worthy'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '29',
    name: 'Sidewalk Espresso',
    category: 'cafe',
    description: 'European-style sidewalk cafe for people watching',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
    tags: ['Espresso', 'Outdoor Seating', 'European'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '30',
    name: 'Cat Cafe Purrfection',
    category: 'cafe',
    description: 'Sip coffee while cuddling adoptable cats',
    priceLevel: 2,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    tags: ['Cats', 'Unique', 'Cozy'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },

  // NIGHTLIFE - Dancing & Clubs
  {
    id: '31',
    name: 'Club Neon',
    category: 'nightlife',
    description: 'High-energy dance club with top DJs',
    priceLevel: 3,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?w=400',
    tags: ['Dancing', 'DJ', 'Dance Floor', 'Late Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'dancing',
  },
  {
    id: '56',
    name: 'Salsa Social Club',
    category: 'nightlife',
    description: 'Latin dance nights with live bands and lessons',
    priceLevel: 2,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=400',
    tags: ['Dancing', 'Salsa', 'Latin', 'Live Music', 'Dance Floor'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'dancing',
  },
  {
    id: '57',
    name: 'Electric Warehouse',
    category: 'nightlife',
    description: 'Underground EDM venue with world-class sound system',
    priceLevel: 3,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=400',
    tags: ['Dancing', 'DJ', 'EDM', 'Dance Floor', 'Events'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'dancing',
  },
  {
    id: '58',
    name: 'Swing Dance Hall',
    category: 'nightlife',
    description: 'Retro swing and jazz dancing with live orchestra',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=400',
    tags: ['Dancing', 'Swing', 'Live Music', 'Dance Floor', 'Vintage'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'dancing',
  },
  {
    id: '59',
    name: 'Hip Hop Fridays',
    category: 'nightlife',
    description: 'Weekly hip hop and R&B dance party',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
    tags: ['Dancing', 'DJ', 'Hip Hop', 'Dance Floor', 'Events'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'dancing',
  },
  {
    id: '60',
    name: 'Country Line Dance Bar',
    category: 'nightlife',
    description: 'Two-step and line dancing with live country music',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=400',
    tags: ['Dancing', 'Country', 'Live Music', 'Dance Floor'],
    isOutdoor: false,
    smokingFriendly: true,
    vibeLevel: 'dancing',
  },
  {
    id: '61',
    name: 'Rooftop Dance Party',
    category: 'nightlife',
    description: 'Open-air dancing under the stars with city views',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?w=400',
    tags: ['Dancing', 'DJ', 'Rooftop', 'Dance Floor', 'Events'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'dancing',
  },
  {
    id: '62',
    name: 'Disco Revival Lounge',
    category: 'nightlife',
    description: '70s disco vibes with mirror balls and funk DJs',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400',
    tags: ['Dancing', 'Disco', 'DJ', 'Dance Floor', 'Retro'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'dancing',
  },
  {
    id: '32',
    name: 'Live Music Venue',
    category: 'nightlife',
    description: 'Intimate concerts and emerging artists',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    tags: ['Live Music', 'Indie', 'Standing Room'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '33',
    name: 'Comedy Club',
    category: 'nightlife',
    description: 'Laugh out loud with stand-up comedy shows',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=400',
    tags: ['Comedy', 'Entertainment', '21+'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '34',
    name: 'Pool Hall & Lounge',
    category: 'nightlife',
    description: 'Upscale billiards with craft cocktails',
    priceLevel: 2,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1604948501466-4e9c339b9c24?w=400',
    tags: ['Pool', 'Competitive', 'Chill'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: '35',
    name: 'Hookah Lounge',
    category: 'nightlife',
    description: 'Relaxed atmosphere with premium hookah & tea',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400',
    tags: ['Hookah', 'Lounge', 'Social'],
    isOutdoor: false,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '36',
    name: 'Outdoor Cinema',
    category: 'nightlife',
    description: 'Movies under the stars with blankets & snacks',
    priceLevel: 2,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    tags: ['Movies', 'Romantic', 'Seasonal'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },

  // WELLNESS
  {
    id: '37',
    name: 'Hot Springs Spa',
    category: 'wellness',
    description: 'Natural hot springs with massage services',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    tags: ['Spa', 'Relaxation', 'Healing'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '38',
    name: 'Yoga in the Park',
    category: 'wellness',
    description: 'Outdoor yoga sessions for all levels',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    tags: ['Yoga', 'Outdoor', 'Peaceful'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '39',
    name: 'Float Tank Center',
    category: 'wellness',
    description: 'Sensory deprivation tanks for deep relaxation',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    tags: ['Unique', 'Meditation', 'Wellness'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '40',
    name: 'Sound Bath Studio',
    category: 'wellness',
    description: 'Healing sound sessions with singing bowls',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    tags: ['Sound Healing', 'Meditation', 'Spiritual'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },

  // FREE ACTIVITIES
  {
    id: '41',
    name: 'Public Library Reading Room',
    category: 'activity',
    description: 'Cozy reading corners and quiet study spaces',
    priceLevel: 1,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=400',
    tags: ['Free', 'Quiet', 'Books'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '42',
    name: 'City Park Picnic',
    category: 'activity',
    description: 'Pack a lunch and enjoy green space and fresh air',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
    tags: ['Free', 'Outdoors', 'Relaxing'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '43',
    name: 'Free Art Museum Day',
    category: 'activity',
    description: 'Explore local art on community free admission days',
    priceLevel: 1,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=400',
    tags: ['Free', 'Art', 'Culture'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '44',
    name: 'Farmers Market Stroll',
    category: 'activity',
    description: 'Browse local produce, artisan goods, and live music',
    priceLevel: 1,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=400',
    tags: ['Free', 'Local', 'Food'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '45',
    name: 'Sunset Beach Walk',
    category: 'activity',
    description: 'Watch the sun dip below the horizon on the shore',
    priceLevel: 1,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400',
    tags: ['Free', 'Romantic', 'Beach'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '46',
    name: 'Street Art Walking Tour',
    category: 'activity',
    description: 'Discover murals and graffiti art in the city',
    priceLevel: 1,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=400',
    tags: ['Free', 'Art', 'Urban'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '47',
    name: 'Community Basketball Courts',
    category: 'activity',
    description: 'Drop-in pickup games at local public courts',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    tags: ['Free', 'Sports', 'Social'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '48',
    name: 'Stargazing Spot',
    category: 'activity',
    description: 'Find a dark spot and watch the night sky',
    priceLevel: 1,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400',
    tags: ['Free', 'Romantic', 'Nature'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '49',
    name: 'Dog Park Hangout',
    category: 'activity',
    description: 'Let your pup play while you socialize',
    priceLevel: 1,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400',
    tags: ['Free', 'Dogs', 'Social'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '50',
    name: 'Free Outdoor Concert',
    category: 'activity',
    description: 'Live music in the park on summer evenings',
    priceLevel: 1,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400',
    tags: ['Free', 'Music', 'Community'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: '51',
    name: 'Window Shopping District',
    category: 'activity',
    description: 'Browse boutiques and people-watch downtown',
    priceLevel: 1,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=400',
    tags: ['Free', 'Shopping', 'Urban'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '52',
    name: 'Meditation in the Park',
    category: 'wellness',
    description: 'Find a quiet bench and practice mindfulness',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    tags: ['Free', 'Meditation', 'Peaceful'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: '53',
    name: 'Bike Path Adventure',
    category: 'activity',
    description: 'Explore scenic routes on two wheels',
    priceLevel: 1,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=400',
    tags: ['Free', 'Exercise', 'Outdoors'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: '54',
    name: 'Public Garden Stroll',
    category: 'activity',
    description: 'Wander through blooming flowers and peaceful paths',
    priceLevel: 1,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    tags: ['Free', 'Nature', 'Relaxing'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: '55',
    name: 'Skatepark Session',
    category: 'activity',
    description: 'Practice tricks or watch the locals shred',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?w=400',
    tags: ['Free', 'Sports', 'Youth'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'active',
  },
];

// BRUNCH SPOTS
export const BRUNCH_SPOTS: Spot[] = [
  {
    id: 'brunch-1',
    name: 'The Sunny Side',
    category: 'brunch',
    cuisine: 'American',
    description: 'Classic American brunch with endless mimosas',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400',
    tags: ['Mimosas', 'Eggs Benedict', 'Weekend Vibes'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'brunch-2',
    name: 'Maple & Vine',
    category: 'brunch',
    cuisine: 'Farm-to-Table',
    description: 'Organic farm-fresh ingredients with a seasonal menu',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=400',
    tags: ['Organic', 'Healthy', 'Instagram-worthy'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'brunch-3',
    name: 'Waffle House Deluxe',
    category: 'brunch',
    cuisine: 'Belgian',
    description: 'Gourmet Belgian waffles with creative toppings',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=400',
    tags: ['Waffles', 'Sweet', 'Family-friendly'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'brunch-4',
    name: 'Chilaquiles Cantina',
    category: 'brunch',
    cuisine: 'Mexican',
    description: 'Authentic Mexican brunch with spicy chilaquiles',
    priceLevel: 2,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=400',
    tags: ['Mexican', 'Spicy', 'Margaritas'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
  {
    id: 'brunch-5',
    name: 'The Avocado Toast Co.',
    category: 'brunch',
    cuisine: 'Californian',
    description: 'Trendy spot specializing in avocado-everything',
    priceLevel: 3,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400',
    tags: ['Avocado', 'Trendy', 'Healthy'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'brunch-6',
    name: 'Biscuits & Gravy House',
    category: 'brunch',
    cuisine: 'Southern',
    description: 'Hearty Southern comfort brunch classics',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400',
    tags: ['Southern', 'Comfort Food', 'Budget-friendly'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'brunch-7',
    name: 'Crepe Studio',
    category: 'brunch',
    cuisine: 'French',
    description: 'Sweet and savory French crepes made to order',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400',
    tags: ['Crepes', 'French', 'Sweet & Savory'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'brunch-8',
    name: 'Bottomless Brunch Club',
    category: 'brunch',
    cuisine: 'Fusion',
    description: 'Unlimited drinks with creative fusion dishes',
    priceLevel: 3,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400',
    tags: ['Bottomless', 'Party Brunch', 'Groups'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'active',
  },
];

// Combine all spots
SAMPLE_SPOTS.push(...BRUNCH_SPOTS);

// LUNCH SPOTS
export const LUNCH_SPOTS: Spot[] = [
  {
    id: 'lunch-1',
    name: 'The Deli Counter',
    category: 'lunch',
    cuisine: 'American',
    description: 'Classic deli sandwiches piled high',
    priceLevel: 1,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400',
    tags: ['Sandwiches', 'Quick', 'Takeout'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'lunch-2',
    name: 'Pho House',
    category: 'lunch',
    cuisine: 'Vietnamese',
    description: 'Steaming bowls of authentic Vietnamese pho',
    priceLevel: 1,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400',
    tags: ['Soup', 'Noodles', 'Healthy'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'lunch-3',
    name: 'Power Bowl Kitchen',
    category: 'lunch',
    cuisine: 'Health Food',
    description: 'Build-your-own grain and protein bowls',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    tags: ['Healthy', 'Bowls', 'Fresh'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'lunch-4',
    name: 'Pizza By The Slice',
    category: 'lunch',
    cuisine: 'Italian',
    description: 'New York style pizza by the slice',
    priceLevel: 1,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    tags: ['Pizza', 'Quick Bite', 'Casual'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'lunch-5',
    name: 'Falafel Corner',
    category: 'lunch',
    cuisine: 'Middle Eastern',
    description: 'Fresh falafel wraps and mezze platters',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?w=400',
    tags: ['Vegetarian', 'Wraps', 'Mediterranean'],
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'lunch-6',
    name: 'Sushi Express',
    category: 'lunch',
    cuisine: 'Japanese',
    description: 'Fast-casual sushi and bento boxes',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400',
    tags: ['Sushi', 'Bento', 'Quick'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
];

// DINNER SPOTS
export const DINNER_SPOTS: Spot[] = [
  {
    id: 'dinner-1',
    name: 'The Steakhouse',
    category: 'dinner',
    cuisine: 'American',
    description: 'Prime cuts and classic sides',
    priceLevel: 4,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
    tags: ['Steak', 'Fine Dining', 'Date Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'dinner-2',
    name: 'Pasta Fresca',
    category: 'dinner',
    cuisine: 'Italian',
    description: 'Handmade pasta in a cozy trattoria',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400',
    tags: ['Pasta', 'Romantic', 'Wine'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'dinner-3',
    name: 'Thai Orchid',
    category: 'dinner',
    cuisine: 'Thai',
    description: 'Authentic Thai curries and stir-fries',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400',
    tags: ['Thai', 'Spicy', 'BYOB'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'dinner-4',
    name: 'Seafood Shack',
    category: 'dinner',
    cuisine: 'Seafood',
    description: 'Fresh catches and ocean views',
    priceLevel: 3,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400',
    tags: ['Seafood', 'Waterfront', 'Fresh'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'chill',
  },
  {
    id: 'dinner-5',
    name: 'Indian Spice',
    category: 'dinner',
    cuisine: 'Indian',
    description: 'Rich curries and fresh naan from the tandoor',
    priceLevel: 2,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    tags: ['Indian', 'Curry', 'Vegetarian Options'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'dinner-6',
    name: 'The Tapas Bar',
    category: 'dinner',
    cuisine: 'Spanish',
    description: 'Small plates perfect for sharing',
    priceLevel: 3,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=400',
    tags: ['Tapas', 'Sharing', 'Wine'],
    isOutdoor: true,
    smokingFriendly: true,
    vibeLevel: 'moderate',
  },
];

// DESSERT SPOTS
export const DESSERT_SPOTS: Spot[] = [
  {
    id: 'dessert-1',
    name: 'Scoops Ice Cream',
    category: 'desserts',
    description: 'Artisan ice cream with unique flavors',
    priceLevel: 2,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400',
    tags: ['Ice Cream', 'Sweet', 'Family-friendly'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'dessert-2',
    name: 'Macaron Boutique',
    category: 'desserts',
    description: 'French macarons in every color and flavor',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=400',
    tags: ['Macarons', 'French', 'Gifts'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'dessert-3',
    name: 'Churros & Chocolate',
    category: 'desserts',
    description: 'Hot churros with rich dipping chocolate',
    priceLevel: 1,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
    tags: ['Churros', 'Chocolate', 'Late Night'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'dessert-4',
    name: 'The Cheesecake Factory',
    category: 'desserts',
    description: 'Over 30 varieties of decadent cheesecake',
    priceLevel: 2,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400',
    tags: ['Cheesecake', 'Indulgent', 'Variety'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'dessert-5',
    name: 'Bubble Waffle House',
    category: 'desserts',
    description: 'Hong Kong style bubble waffles with toppings',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    tags: ['Waffles', 'Instagram-worthy', 'Unique'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'dessert-6',
    name: 'Mochi Bar',
    category: 'desserts',
    description: 'Japanese mochi ice cream and desserts',
    priceLevel: 2,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1631206753348-db44968fd440?w=400',
    tags: ['Mochi', 'Japanese', 'Cute'],
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
];

// Add new meal categories to spots
SAMPLE_SPOTS.push(...LUNCH_SPOTS, ...DINNER_SPOTS, ...DESSERT_SPOTS);

// Add neighborhoods to existing spots for richer display
const neighborhoods = [
  'Downtown', 'Midtown', 'Arts District', 'Old Town', 'Uptown',
  'Westside', 'East Village', 'North End', 'Southside', 'Harbor District',
  'Historic Quarter', 'Riverside', 'The Heights', 'Market Square', 'Lakeview',
];
SAMPLE_SPOTS.forEach((spot, i) => {
  if (!spot.neighborhood) {
    spot.neighborhood = neighborhoods[i % neighborhoods.length];
  }
});

// EVENT PLANNING RESOURCES (Plus-only)
export const EVENT_PLANNING_SPOTS: Spot[] = [
  {
    id: 'ep-1',
    name: 'Grand Ballroom at The Monarch',
    category: 'activity',
    description: 'Elegant ballroom venue for weddings and galas up to 500 guests',
    priceLevel: 4,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400',
    tags: ['Venue', 'Weddings', 'Corporate'],
    neighborhood: 'Downtown',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'ep-2',
    name: 'DJ Spinmaster Productions',
    category: 'activity',
    description: 'Professional DJ and MC services for all event types',
    priceLevel: 3,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?w=400',
    tags: ['DJ', 'Music', 'Entertainment'],
    neighborhood: 'Arts District',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: 'ep-3',
    name: 'Savory Affairs Catering',
    category: 'restaurant',
    description: 'Full-service catering with custom menus and staff',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=400',
    tags: ['Catering', 'Custom Menu', 'Full Service'],
    neighborhood: 'Midtown',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'ep-4',
    name: 'Lens & Light Photography',
    category: 'wellness',
    description: 'Award-winning event photography and videography',
    priceLevel: 3,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=400',
    tags: ['Photography', 'Videography', 'Memories'],
    neighborhood: 'East Village',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'ep-5',
    name: 'SoundStage AV Rentals',
    category: 'activity',
    description: 'Pro audio-visual equipment and production crews',
    priceLevel: 3,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400',
    tags: ['AV', 'Production', 'Sound & Lights'],
    neighborhood: 'Westside',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
  {
    id: 'ep-6',
    name: 'Bloom & Co. Florals',
    category: 'shopping',
    description: 'Stunning floral arrangements and event décor',
    priceLevel: 3,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400',
    tags: ['Florist', 'Décor', 'Design'],
    neighborhood: 'Old Town',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'chill',
  },
  {
    id: 'ep-7',
    name: 'Elite Event Rentals',
    category: 'shopping',
    description: 'Tables, chairs, tents, linens — everything you need',
    priceLevel: 2,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1478146059778-26028b07395a?w=400',
    tags: ['Rentals', 'Tents', 'Furniture'],
    neighborhood: 'Southside',
    plusOnly: true,
    isOutdoor: true,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'ep-8',
    name: 'Metro VIP Transport',
    category: 'activity',
    description: 'Luxury shuttles and party buses for group transport',
    priceLevel: 3,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400',
    tags: ['Transportation', 'Shuttle', 'Luxury'],
    neighborhood: 'Harbor District',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'moderate',
  },
  {
    id: 'ep-9',
    name: 'ProStaff Event Services',
    category: 'wellness',
    description: 'Bartenders, servers, and event coordinators on demand',
    priceLevel: 2,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
    tags: ['Staffing', 'Bartenders', 'Coordinators'],
    neighborhood: 'Uptown',
    plusOnly: true,
    isOutdoor: false,
    smokingFriendly: false,
    vibeLevel: 'active',
  },
];

SAMPLE_SPOTS.push(...EVENT_PLANNING_SPOTS);
